### ISSUE TITLE
publisher在小米2S上闪退在华为P8上只能推送一帧

### ISSUE THREAD

**Issue by OhYee** [blueberryCoder/LiveStream#12]
直接把下载的源码编译运行

小米2S报错如下

```
java.lang.RuntimeException: Unable to resume activity {com.blueberry.sample/com.blueberry.sample.MainActivity}: java.lang.RuntimeException: setParameters failed
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2966)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2997)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2380)
	at android.app.ActivityThread.access$900(ActivityThread.java:147)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
Caused by: java.lang.RuntimeException: setParameters failed
	at android.hardware.Camera.native_setParameters(Native Method)
	at android.hardware.Camera.setParameters(Camera.java:1979)
	at com.blueberry.media.VideoGatherer.setCameraParameters(VideoGatherer.java:247)
	at com.blueberry.media.VideoGatherer.initCamera(VideoGatherer.java:90)
	at com.blueberry.media.MediaPublisher.initVideoGatherer(MediaPublisher.java:101)
	at com.blueberry.sample.MainActivity.onResume(MainActivity.java:84)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
	at android.app.Activity.performResume(Activity.java:6025)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2955)
	... 11 more

```

华为P8图像推送出去一帧图像，但是声音能正常推送

其他手机测试没问题

——————————————————————————
另外 `Rtmp.cpp`在build apk的时候，提示`malloc`未定义，需要手动补上`malloc.h`头文件

**Comment by wuzhenzhen** [comment]
荣耀7 也是只能推送一帧呀，如何解决？
